"""Task construction for the SPhyR benchmark: dataset records in, prompts out.

This module holds everything needed to turn a SPhyR dataset record into the
prompt an agent is shown.  It is deliberately free of any model, provider or
scoring code so that the OpenEnv environment in ``sphyr_env`` can build its
observations from it.
"""

import json
import random
from dataclasses import dataclass, replace
from pathlib import Path

from sphyr.metrics.utils import extract_grid_from_text
from sphyr.prompt_templates import (
    FEEDBACK_PROMPT_TEMPLATE,
    FEW_SHOT_EXAMPLES,
    FEW_SHOT_PROMPT_TEMPLATE,
    PHYSICS_ENHANCED_PROMPT_TEMPLATE,
    PHYSICS_NEUTRAL_PROMPT_TEMPLATE,
    PROMPT_TEMPLATE,
)

SUBJECTS = [
    "1_random_cell_easy",
    "5_random_cell_easy",
    "10_random_cell_easy",
    "1_random_row_easy",
    "3_random_row_easy",
    "1_random_column_easy",
    "3_random_column_easy",
    "full_easy",
    "1_random_cell_hard",
    "5_random_cell_hard",
    "10_random_cell_hard",
    "1_random_row_hard",
    "3_random_row_hard",
    "1_random_column_hard",
    "3_random_column_hard",
    "full_hard",
]

RANDOM_SEED = 42
SAMPLE_COUNT = 100

HF_DATASET_ID = "philippds/SPhyR"

# The generated datasets ship with the repository, so an episode can be built
# without network access.  The Hugging Face hub copy is the same data.
DATASET_DIR = (
    Path(__file__).parent / "dataset_creation" / "huggingface" / "2D" / "datasets"
)

# The dataset versions that ship with the repository.  ``v1`` is the published
# benchmark; the ``v2`` sets are regenerated by
# ``sphyr.dataset_creation.generate_v2`` over a boundary-condition space whose
# samples are held far apart, so that a sample cannot be answered by copying a
# neighbour's solution.  ``v2-20`` is the same construction on a 20x20 grid.
DATASET_VERSIONS = {
    "v1": DATASET_DIR,
    "v2": DATASET_DIR.parent / "datasets_v2",
    "v2-20": DATASET_DIR.parent / "datasets_v2_20",
}
DEFAULT_DATASET_VERSION = "v1"


def dataset_dir(version=DEFAULT_DATASET_VERSION):
    """Directory holding one dataset version's subject files."""
    if version not in DATASET_VERSIONS:
        raise ValueError(
            f"Unknown dataset version {version!r}; expected one of "
            f"{', '.join(DATASET_VERSIONS)}"
        )
    return DATASET_VERSIONS[version]

# Prompt variants used by the experiments.  The template is part of the task,
# not of the runner, so it is selected by name on reset().
PROMPT_STYLES = {
    "default": PROMPT_TEMPLATE,
    "feedback": FEEDBACK_PROMPT_TEMPLATE,
    "physics_enhanced": PHYSICS_ENHANCED_PROMPT_TEMPLATE,
    "physics_neutral": PHYSICS_NEUTRAL_PROMPT_TEMPLATE,
}

BINARY_FILL_INSTRUCTION = "'V' cells with either '1' (solid) or '0' (empty)"
DENSITY_FILL_INSTRUCTION = (
    "'V' cells with a floating point number between 0 and 1, with one decimal "
    "place (e.g., 0.0, 0.1, 0.2, ..., 1.0)"
)


@dataclass
class Sample:
    """One SPhyR episode: a masked grid, the prompt for it, and its answer."""

    subject: str
    index: int
    input: str
    prompt: str
    ground_truth: str
    rotation_count: int = 0
    cell_values: str = "binary"
    rows: int = 0
    cols: int = 0
    masked_cells: int = 0


def grid_to_str(grid):
    """Render a grid as text, accepting either a nested list or text already.

    The dataset files store grids as nested lists while prompts and completions
    carry them as text, so every entry point normalises through here.
    """
    if isinstance(grid, str):
        return grid.strip()
    return "\n".join(" ".join(str(cell) for cell in row) for row in grid)


def str_to_grid(grid):
    """Parse grid text back into a nested list of cell tokens."""
    return [line.split() for line in grid_to_str(grid).splitlines() if line.split()]


def rotate_grid(grid, times=1):
    """Rotate a grid 90 degrees clockwise ``times`` times."""
    rows = str_to_grid(grid)
    for _ in range(times % 4):
        rows = [list(row) for row in zip(*rows[::-1])]
    return "\n".join(" ".join(row) for row in rows)


def gravity_for_rotation(rotation_count):
    """The direction force flows through a grid rotated ``rotation_count`` times.

    Rotating the sample rotates its load case with it, so the metrics that care
    about force direction have to be told where "down" ended up.  Returns a
    ``(dr, dc)`` step; ``(1, 0)`` is top to bottom, the unrotated default.
    """
    return {0: (1, 0), 1: (0, -1), 2: (-1, 0), 3: (0, 1)}[rotation_count % 4]


def is_density_subject(subject):
    """``hard`` subjects are completed with densities, ``easy`` ones with 0/1."""
    return subject.endswith("hard")


def fill_instruction_for(subject):
    if is_density_subject(subject):
        return DENSITY_FILL_INSTRUCTION
    return BINARY_FILL_INSTRUCTION


def resolve_prompt_template(prompt_style):
    """Look a prompt style up by name, or pass a template through unchanged."""
    if prompt_style in PROMPT_STYLES:
        return PROMPT_STYLES[prompt_style]
    if "{GRID}" in prompt_style:
        return prompt_style
    raise ValueError(
        f"Unknown prompt style {prompt_style!r}; expected one of "
        f"{sorted(PROMPT_STYLES)} or a template containing a GRID placeholder"
    )


def format_feedback(metrics):
    """Describe, in words, how a submitted structure behaved under simulation.

    Deliberately physical and deliberately incomplete: it reports what the
    structure did -- whether it stood, how stiff it was for the material spent,
    how much material that was -- and never which cells were wrong.  A model
    given this is being handed grounding it cannot compute for itself, not the
    answer it was asked for.
    """
    if not metrics.get("valid_output_grid", False):
        return (
            "- The reply could not be read as a grid of the right shape, so it "
            "could not be simulated."
        )

    lines = []
    if not metrics.get("load_carrying", False):
        lines.append(
            "- It did NOT carry the load: force reached no support through "
            "material, so the structure is not standing."
        )
    else:
        lines.append("- It carried the load.")

    structural = metrics.get("structural_efficiency")
    if structural is not None:
        lines.append(
            f"- Stiffness against the best design at this material budget: "
            f"{100.0 * structural:.0f}% (100% would match it)."
        )

    volume = metrics.get("volume_ratio")
    if volume is not None:
        if volume > 1.05:
            lines.append(
                f"- It used {100.0 * (volume - 1.0):.0f}% MORE material than the "
                "budget allows; remove material that is not carrying load."
            )
        elif volume < 0.95:
            lines.append(
                f"- It used {100.0 * (1.0 - volume):.0f}% less material than the "
                "budget allows."
            )
        else:
            lines.append("- Its material use matched the budget.")

    islands = metrics.get("isolated_clusters_count")
    if islands:
        lines.append(
            f"- {int(islands)} cluster(s) of material are connected to no load "
            "and no support, and carry nothing."
        )

    return "\n".join(lines)


def load_subject(subject, source=None, version=DEFAULT_DATASET_VERSION):
    """Load one subject's records, from the bundled files or the hub.

    ``source`` is ``"local"``, ``"hub"``, or ``None`` to prefer the bundled
    copy and fall back to the hub when it is missing.  ``version`` selects a
    dataset version from :data:`DATASET_VERSIONS`; only ``v1`` is published on
    the hub, so the regenerated versions are always read from disk.
    """
    if subject not in SUBJECTS:
        raise ValueError(f"Unknown subject {subject!r}; expected one of {SUBJECTS}")

    path = dataset_dir(version) / f"{subject}.jsonl"

    if source == "local" or version != DEFAULT_DATASET_VERSION or path.exists():
        if not path.exists():
            raise FileNotFoundError(f"Dataset file not found: {path}")
        with open(path, "r") as handle:
            return [json.loads(line) for line in handle if line.strip()]

    from datasets import load_dataset

    return list(load_dataset(HF_DATASET_ID, subject)["test"])


def count_masked_cells(input_grid):
    return sum(row.count("V") for row in str_to_grid(input_grid))


def create_few_shot_example(
    dataset, current_record, few_shot_count, rotation_count, rng
):
    """Draw ``few_shot_count`` solved examples that are not the sample itself."""
    few_shot_examples = rng.sample(dataset, few_shot_count + 1)
    few_shot_examples = [
        example
        for example in few_shot_examples
        if example["input_grid"] != current_record["input_grid"]
    ]
    few_shot_examples = few_shot_examples[:few_shot_count]

    return "\n\n".join(
        FEW_SHOT_EXAMPLES.format(
            EXAMPLE_GRID=rotate_grid(example["input_grid"], times=rotation_count),
            EXAMPLE_COMPLETED_GRID=rotate_grid(
                example["ground_truth"], times=rotation_count
            ),
        )
        for example in few_shot_examples
    )


def build_sample(
    dataset,
    record,
    index,
    subject,
    rotation_count=0,
    few_shot_count=0,
    prompt_template=PROMPT_TEMPLATE,
    few_shot_prompt_template=FEW_SHOT_PROMPT_TEMPLATE,
    rng=None,
):
    """Turn one dataset record into a ready-to-serve :class:`Sample`."""
    input_grid = rotate_grid(record["input_grid"], times=rotation_count)
    ground_truth = rotate_grid(record["ground_truth"], times=rotation_count)
    fill_instruction = fill_instruction_for(subject)

    if few_shot_count > 0:
        prompt = few_shot_prompt_template.format(
            FILL_INSTRUCTION=fill_instruction,
            FEW_SHOT_EXAMPLES=create_few_shot_example(
                dataset, record, few_shot_count, rotation_count, rng or random
            ),
            GRID=input_grid,
        )
    else:
        prompt = prompt_template.format(
            FILL_INSTRUCTION=fill_instruction,
            GRID=input_grid,
        )

    rows = str_to_grid(input_grid)

    return Sample(
        subject=subject,
        index=index,
        input=input_grid,
        prompt=prompt,
        ground_truth=ground_truth,
        rotation_count=rotation_count,
        cell_values="density" if is_density_subject(subject) else "binary",
        rows=len(rows),
        cols=len(rows[0]) if rows else 0,
        masked_cells=count_masked_cells(input_grid),
    )


# The results the paper reports, used to replay the exact samples a published
# column was produced on.  The repository root is three levels up from here.
PUBLISHED_RESULTS_ROOT = Path(__file__).parent.parent.parent / "results"


def published_records(subject, replay_from, results_root=None):
    """The stored records of one published run, in the order it saw them."""
    root = Path(results_root) if results_root else PUBLISHED_RESULTS_ROOT
    path = root / replay_from / f"{subject}_results.json"

    if not path.exists():
        raise FileNotFoundError(
            f"No published results to replay at {path}; replay_from names a "
            "directory under results/, e.g. 'claude-opus-4-20250514'"
        )

    with open(path, "r") as handle:
        return json.load(handle)


def replay_samples(subject, records, rotation_count=0):
    """Rebuild the samples a published run was scored on, from its own records.

    The published samples cannot be regenerated from the dataset.  Every
    subject that masks a *random* region -- all but ``full_easy`` and
    ``full_hard`` -- had its masks re-rolled when the dataset files were
    regenerated, so the grids those runs were scored on no longer exist in the
    dataset: of the 100 samples behind each published column, between 0 and 14
    are still reproducible from it.

    They survive in the results files, which store the prompt and the answer
    for every completion, and a prompt plus its ground truth is the whole task.
    Reconstructing from those is therefore not a convenience but the only way a
    new model can be measured on the samples the published columns were
    measured on.
    """
    samples = []

    for index, record in enumerate(records):
        prompt = record["prompt"]
        input_grid = grid_to_str(extract_grid_from_text(prompt))
        rows = str_to_grid(input_grid)

        samples.append(
            Sample(
                subject=subject,
                index=index,
                input=input_grid,
                prompt=prompt,
                ground_truth=record["ground_truth"],
                rotation_count=rotation_count,
                cell_values="density" if is_density_subject(subject) else "binary",
                rows=len(rows),
                cols=len(rows[0]) if rows else 0,
                masked_cells=count_masked_cells(input_grid),
            )
        )

    return samples


def generate_prompts(
    dataset,
    subject,
    sample_count=SAMPLE_COUNT,
    rotation_count=0,
    few_shot_count=0,
    prompt_template=PROMPT_TEMPLATE,
    few_shot_prompt_template=FEW_SHOT_PROMPT_TEMPLATE,
    rng=None,
) -> list[Sample]:
    """Build the prompts for one subject, in dataset order."""
    return [
        build_sample(
            dataset=dataset,
            record=record,
            index=index,
            subject=subject,
            rotation_count=rotation_count,
            few_shot_count=few_shot_count,
            prompt_template=prompt_template,
            few_shot_prompt_template=few_shot_prompt_template,
            rng=rng,
        )
        for index, record in enumerate(dataset[:sample_count])
    ]
